services:
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: signme-backend
        container_name: signme-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - storage_data:/var/www/storage
        environment:
            APP_NAME: ${APP_NAME:-signme}
            APP_ENV: ${APP_ENV:-production}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG:-true}
            APP_URL: ${APP_URL:-https://api.signmehere.cloud}
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE:-signme}
            DB_USERNAME: ${DB_USERNAME:-signme}
            DB_PASSWORD: ${DB_PASSWORD:-password}
            CACHE_STORE: redis
            REDIS_HOST: redis
            SESSION_DRIVER: database
            SESSION_DOMAIN: .signmehere.cloud
            SANCTUM_STATEFUL_DOMAINS: signmehere.cloud,api.signmehere.cloud
            LOG_CHANNEL: stderr
        networks:
            - signme-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_BACKEND_URL: "https://api.signmehere.cloud/"
        image: signme-frontend
        container_name: signme-frontend
        restart: unless-stopped
        networks:
            - signme-network

    db:
        image: mysql:8.0
        container_name: signme-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-signme}
            MYSQL_USER: ${DB_USERNAME:-signme}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - signme-network

    redis:
        image: redis:alpine
        container_name: signme-redis
        restart: unless-stopped
        networks:
            - signme-network
    reverb:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: signme-backend
        container_name: signme-reverb
        restart: unless-stopped
        command: "php artisan reverb:start --host=0.0.0.0 --port=8080"
        networks:
            - signme-network
        depends_on:
            - app
            - db
            - redis

networks:
    signme-network:
        driver: bridge

volumes:
    dbdata:
    storage_data:
